# Generated by Django 5.1.4 on 2024-12-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
