# Generated by Django 5.1.4 on 2024-12-11 01:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57494a4a-5501-45c6-b7ee-cb3dc0f2d098'), editable=False, primary_key=True, serialize=False),
        ),
    ]
