# Generated by Django 5.1.4 on 2024-12-11 01:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9af06300-e23d-4ff5-bf22-6f8f616219bd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
