# Generated by Django 5.1.4 on 2024-12-11 01:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5bf1ee7a-1a58-4970-826a-6f89f35a35bd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
