# Generated by Django 5.1.4 on 2024-12-11 01:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('78950a84-9220-46bc-97b1-4c358e01097c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
