# Generated by Django 5.1.4 on 2024-12-11 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_id_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3a50595-8817-41f7-8c80-ae6a7942d836'), editable=False, primary_key=True, serialize=False),
        ),
    ]
