# Generated by Django 5.1.4 on 2024-12-13 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_created_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4da595a-d327-4b27-a1b9-f488e834c2a5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
