# Generated by Django 5.1.4 on 2024-12-13 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47599cb5-7a48-49b8-b23c-b7cbd76282fb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
