# Generated by Django 5.1.4 on 2024-12-14 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7e34a6f-45d3-4fd9-9903-6519ce0dc67f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
