# Generated by Django 5.1.4 on 2024-12-14 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_profile_is_private_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea3198b9-08ef-4861-8f94-422dd36e3a0f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
