# Generated by Django 5.1.4 on 2024-12-14 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d32d4df2-52e8-401d-a584-05496b14214c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
